### ISSUE TITLE
请求部署详情——订阅消息模板

### ISSUE THREAD

**Issue by huobaolajiao** [zhiiee/cats#1]
您好，这个项目基于北大猫咪项目的2.0版本非常厉害，我是上海海洋大学的同学，正在基于此项目开发《SHOU小流浪图鉴》小程序，需要templateId: 'rrPousHxOgv-Lf5vQMry8xa5CjspYVzfYCjXxFA-ZmI',的具体订阅消息模板信息，否则报错errMsg: "requestSubscribeMessage:fail can only be invoked by user TAP gesture."，也可能是修改中碰到了其他事件绑定。
另外，希望可以添加即时通信具体请教一些问题，谢谢！

**Comment by stephenml** [comment]
这个项目的订阅消息模板需要“社区/论坛”类目，你可以适当修改为自己订阅消息模板。

**Comment by huobaolajiao** [comment]
收到谢谢！将参考配置！另外，我现在正在额外开发其他功能，footprint-service云函数api仿照post-service写的，但是不知api类型为什么是any，这直接导致添加const Footprints = require('./services/footprints-service')和footprints: new Footprints()两行导致云函数服务器宕机，请教函数配置
![image](https://user-images.githubusercontent.com/38094576/101329148-e8e4e000-3868-11eb-8d82-d51f1ca48c86.png)
![image](https://user-images.githubusercontent.com/38094576/101329184-f39f7500-3868-11eb-9ceb-48cedbcc35ad.png)
![image](https://user-images.githubusercontent.com/38094576/101329218-03b75480-3869-11eb-9d4d-ea73b0a6022e.png)

**Comment by stephenml** [comment]
建议先检查下代码问题，然后使用云开发本地调试看下具体报错原因。

**Comment by huobaolajiao** [comment]
已新增1200行[3.0.0](https://github.com/huobaolajiao/cats/commit/0b0f8b3298102fb926e5a7b7e87f0894394eb34d)，在[仓库](https://github.com/huobaolajiao/cats)依法开源，小程序业务已上线：SHOU小流浪图鉴
